### PR TITLE
feat: support slow start and sticky session

### LINKED ISSUE #12: support slow_start mode for ALB target group
As the keycloak application running with JBoss may take longer time to start and enter the ready state, we might need to configure the ALB target group with slow_start attribute and set to something like `60`

see 
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#slow-start-mode
- https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-target-group-attributes.html

### PR DESCRIPTION
**Pull request by pahud**
- support slow start mode
- support sticky session
- make the bastion host optional(default disabled)

Fixes #12 #13

### CODE REVIEW

**Comment by pahud** [comment]
HI @wchaws 

I can successfully deploy this in NRT, will try BJS/ZHY next.

**Comment by pahud** [comment]
@mergifyio

**Comment by pahud** [comment]
UPDATE: both BJS and ZHY can be successfully deployed now.

**Comment by wchaws** [comment]
For sticky session
1. This is preferred way but it's not mandatory
2. From the [doc](https://www.keycloak.org/docs/latest/server_installation/index.html#sticky-sessions). Keycloak is going to decide the traffic routing rule. 

    > Keycloak creates the cookie AUTH_SESSION_ID with the format like `<session-id>.<owner-node-id>`. for example `123.node2`

    I think ALB should be able to parse that cookie and dispatch the traffic based on the cookie. I'm not sure if AWS ALB support that feature

Again, this is a nice to have feature.

**Pull request merged**
